/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
  }
}
